$font = "FiraCode Nerd Font"

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/von/Pictures/wallpapers/arch-black.png
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(255, 248, 240, 0.0)   # soft cream

    outer_color = rgba(139, 69, 19, 0.9) rgba(205, 133, 63, 0.9) 45deg
    check_color = rgba(222, 184, 135, 1) rgba(255, 228, 196, 1) 120deg
    fail_color = rgba(165, 42, 42, 0.9) rgba(128, 0, 0, 0.9) 40deg

    font_color = rgb(60, 42, 20)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL

    dots_spacing = 0.3
    position = 0, -20
    halign = center
    valign = center
}

label {  # TIME
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    font_color = rgb(92, 64, 51)
    position = -30, 0
    halign = right
    valign = top
}

label {  # DATE
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font
    font_color = rgb(110, 85, 70)
    position = -30, -150
    halign = right
    valign = top
}
